version: '3.8'

services:
  web:
    build: .
    image: osvasldas97/kainos-scraper:latest
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
